name = "GSReg"
uuid = "fcdd16ba-c1f8-11e8-2198-bf28db4a5c94"
authors = ["Demian Panigo <panigo@gmail.com>", "Valentin Mari <valentinmari@hotmail.com>", "Adán Mauri Ungaro <adan.mauri@gmail.com>"]
version = "0.0.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
